name: "vgan_haplocart"
description: Human mtDNA haplogroup classification
keywords:
  - mtDNA
  - mitochondria
  - pangenome
  - haplogroup
  - variation graph
tools:
  - "vgan":
      description: "Suite of tools for pangenomics built using vg"
      homepage: "https://github.com/grenaud/vgan"
      documentation: "https://github.com/grenaud/vgan"
      tool_dev_url: "https://github.com/grenaud/vgan"
      doi: ""
      licence: "['GPL v3']"

input:
  - INPUT1:
      type: file
      description: Input file
      pattern: "*.{fq,fq.gz,fastq,fastq.gz}"

  - INPUT2:
      type: file
      description: Optional second FASTQ file for non-interleaved paired-end reads
      pattern: "*.{fq,fq.gz,fastq,fastq.gz}"

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - txt:
      type: file
      description: HaploCart output file with predicted mtDNA haplogroup
      pattern: "*.{txt}"

  - posterior:
      type: file
      description: HaploCart posterior output file
      pattern: "*.{posterior.txt}"

authors:
  - "@JoshuaDanielRubin"
